<?xml version="1.0"?>
<robot name="diffbot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- ================= PARAMETERS ================= -->
  <xacro:property name="wheel_radius" value="0.034"/>
  <xacro:property name="wheel_separation" value="0.264"/>
  <xacro:property name="wheel_width" value="0.03"/>
  <xacro:property name="half_wheel_sep" value="${wheel_separation/2.0}"/>

  <!-- ================= BASE LINK ================= -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="0.3 0.2 0.1"/>
      </geometry>
      <origin xyz="0 0 0.05"/>
    </visual>
  </link>

  <!-- ================= LEFT WHEEL ================= -->
  <link name="left_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="1.5707 0 0"/>
    </visual>
  </link>

  <joint name="left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel"/>
    <!-- y = + half separation -->
    <origin xyz="0 ${half_wheel_sep} ${wheel_radius}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- ================= RIGHT WHEEL ================= -->
  <link name="right_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="1.5707 0 0"/>
    </visual>
  </link>

  <joint name="right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel"/>
    <!-- y = - half separation -->
    <origin xyz="0 -${half_wheel_sep} ${wheel_radius}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- ================= ROS2 CONTROL ================= -->
  <ros2_control name="TeensySystem" type="system">
    <hardware>
      <plugin>diffbot_hardware/DiffBotSystemHardware</plugin>
      <param name="serial_port">/dev/ttyACM0</param>
      <param name="baudrate">115200</param>
    </hardware>

    <joint name="left_wheel_joint">
      <command_interface name="velocity"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>

    <joint name="right_wheel_joint">
      <command_interface name="velocity"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
  </ros2_control>

</robot>
